### ISSUE TITLE
Reason for getComposeViewModel

### ISSUE THREAD

**Issue by lud** [kaleidot725/Jetpack-Compose-Orbit-MVI-Demo#5]
Hello, 

I am trying to implement a simple app, and this is my first android app ; it's quite hard. I chose Orbit and Koin with Jetpack Compose, so this repository is of great help.

Could you tell my the reason why you decided to implement those functions:

```kotlin
@Composable
fun getComposeViewModelOwner(): ViewModelOwner {
    return ViewModelOwner.from(
        LocalViewModelStoreOwner.current!!,
        LocalSavedStateRegistryOwner.current
    )
}

@Composable
inline fun <reified T : ViewModel> getComposeViewModel(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null,
): T {
    val viewModelOwner = getComposeViewModelOwner()
    return KoinJavaComponent.getKoin().getViewModel(qualifier, { viewModelOwner }, parameters)
}
```

Thanks!

**Comment by alexfrostdev** [comment]
Hello @lud, this app uses [Koin](https://insert-koin.io/) lib for dependency injection. So this function create/return already created ViewModel using Koin

**Comment by lud** [comment]
I can't remember why I needed this :D I ended up choosing different technologies for that project, but thank you :)
